name: Deploy bff-api to Cloud Run

on:
  push:
    branches: [ main, master ]
    paths:
      - 'services/bff-api/**'
  workflow_dispatch: {}

permissions:
  contents: 'read'
  id-token: 'write'

env:
  SERVICE_NAME: bff-api
  REGION: us-central1
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up gcloud auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and push image
        run: |
          gcloud builds submit services/bff-api --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$(git rev-parse --short HEAD)

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$(git rev-parse --short HEAD) \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --ingress all

      - name: Output service URL
        run: |
          gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format 'value(status.url)'
