name: Deploy Cloudflare Worker (edge-proxy)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'services/edge-proxy/**'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install wrangler
        run: npm i -g wrangler@4
      - name: Publish worker
        working-directory: services/edge-proxy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          BFF_HOST: ${{ vars.BFF_HOST }}
        run: |
          npx wrangler deploy --var BFF_HOST:${BFF_HOST}
