name: Validate Primary Source Links

on:
  push:
    branches: [ main, master ]
    paths:
      - 'web/src/data/**'
      - 'scripts/verify-sources.mjs'
  schedule:
    - cron: '0 6 * * 1' # weekly, Mondays 06:00 UTC
  workflow_dispatch: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run link verifier
        run: |
          node scripts/verify-sources.mjs --ci || exit 1
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: links-report
          path: reports/links.md


